services:
  - type: web
    name: pdf-convertor-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    workingDir: server
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: pdf-convertor-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    workingDir: client
