services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    workingDir: server
    buildFilter:
      paths:
        - server/**

  - type: web
    name: react-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    workingDir: client
    buildFilter:
      paths:
        - client/**
